version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "pom.xml" }}
          - dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: dependencies-{{ checksum "pom.xml" }}
        
      - run: mvn package

      - store_test_results:
          path: target/surefire-reports
